'$schema' = 'https://starship.rs/config-schema.json'

format = """
[╭](surface2)\
$directory\
$username\
$hostname\
$container\
\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$vcsh\
\
$cmd_duration\
$jobs\
$sudo\
$shlvl\
$status\
\
$buf\
$bun\
$c\
$cmake\
$cobol\
$crystal\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$spack\
$swift\
$vagrant\
$vlang\
$zig\
\
(${env_var.incognito}\
$package\
$nix_shell\
$aws\
$azure\
$docker_context\
$kubernetes\
$terraform)\
\
$line_break\
\
$shell\
[╰](surface2)\
$character"""

add_newline = true
continuation_prompt = '[>](bold subtext0) '
palette = "catppuccin_mocha"

[character]
success_symbol = '[λ](bold text)'
error_symbol = '[λ](bold red)'
vimcmd_symbol = '[](bold cyan)'

[time]
format = ' [$time]($style) '
style = 'fg:subtext0'
disabled = true

[directory]
format = '[$path ]($style)[($read_only)]($read_only_style)'
style = 'fg:red italic'
read_only = ' '
read_only_style = 'fg:red'
truncate_to_repo = true
use_os_path_sep = false

[username]
format = '[$user ]($style)'
style_root = 'fg:red'
style_user = 'fg:red'

[hostname]
format = '[$ssh_symbol$hostname ]($style)'
style = 'fg:red'
ssh_symbol = '@'

[container]
format = '[$hostname ]($style)'
style = 'fg:red'

### VCS
[git_branch]
format = '[$symbol$branch ]($style)'
style = 'fg:peach'
symbol = ' '
ignore_branches = ['main', 'master']

[hg_branch]
format = '[$symbol$branch ]($style)'
style = 'fg:peach'

[git_commit]
format = '[$tag ]($style)'
style = 'fg:peach'
tag_disabled = false
tag_symbol = ' '

[git_state]
format = '[\[$state($progress_current/$progress_total)\] ]($style)'
style = 'fg:peach'
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'fg:peach'
ahead = ' '
behind = ' '
conflicted = '󰩌 '
deleted = '󱪢 '
diverged = '󱐎 '
modified = '󱇨 '
renamed = '󱀱 '
untracked = '󰻭 '
staged = '󱧳 '
stashed = '󱧶 '
disabled = false

### SHELL STATUS
[cmd_duration]
format = '[ $duration ]($style)'
style = 'fg:yellow'
show_milliseconds = true
min_time = 2000

[jobs]
disabled = false
symbol = ' '
style = 'fg:yellow'

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
style = 'fg:yellow'
symbol = ' '
threshold = 3

[status]
format = '[$symbol$status]($style) '
style = 'fg:yellow'
not_executable_symbol = ' '
not_found_symbol = ' '
sigint_symbol = ' '
signal_symbol = '󰞁 '
symbol = '󰌑 '
map_symbol = false
disabled = true

[sudo]
disabled = false
format = '[$symbol ]($style)'
style = 'fg:yellow'
symbol = ' '

### LANGUAGE VERSION INDICATORS
[buf]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[bun]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[c]
format = '[$symbol($version(-$name)) ]($style)'
style = 'fg:green'
symbol = '󰙱 '

[cmake]
format = '[$symbol($version) ]($style)'
symbol = '△'
style = 'fg:green'

[cobol]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[conda]
format = '[$symbol$environment ]($style)'
style = 'fg:green'

[crystal]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[dart]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[deno]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[dotnet]
format = '[$symbol($version)( $tfm) ]($style)'
style = 'fg:green'
symbol = ' '

[elixir]
format = '[$symbol($version \(OTP $otp_version\)) ]($style)'
style = 'fg:green'
symbol = ' '

[elm]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[erlang]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[fennel]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[golang]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[haskell]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[haxe]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[helm]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = '󱃾 '

[java]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[julia]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[kotlin]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[lua]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[nim]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[nix_shell]
format = '[$symbol$state($name) ]($style)'
style = 'fg:blue'
symbol = '󱄅 '
impure_msg = ''
pure_msg = 'pure '

[nodejs]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = '󰎙 '

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\)) ]($style)'
style = 'fg:green'
symbol = ' '

[perl]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[php]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[purescript]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
style = 'fg:green'
symbol = ' '

[red]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = '󱥒 '

[ruby]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[rust]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[scala]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[spack]
format = '[$symbol$environment ]($style)'
style = 'fg:green'

[swift]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

[vagrant]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[vlang]
format = '[$symbol($version) ]($style)'
style = 'fg:green'

[zig]
format = '[$symbol($version) ]($style)'
style = 'fg:green'
symbol = ' '

### PACKAGE INDICATORS
[package]
symbol = ' '
format = '[$symbol$version ]($style)'
style = 'fg:blue'
disabled = false

### CONTEXT INDICATORS
[env_var.incognito]
format = '[$symbol ]($style)'
variable = 'ZSH_INCOGNITO'
style = 'fg:blue'
symbol = '󰗹 '

# these have `disabled` added so we can toggle them via `starship toggle <name>`
[aws]
disabled = false
format = '[$symbol($profile)(\($region\))(\[$duration\]) ]($style)'
style = 'fg:mauve'
symbol = ' '

[azure]
disabled = true
format = '[$symbol($subscription)]($style)'
style = 'fg:mauve'
symbol = ' '

[docker_context]
disabled = false
format = '[$symbol$context ]($style)'
style = 'fg:mauve'
symbol = ' '

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($region\)) ]($style)'
style = 'fg:mauve'
symbol = ' '

[kubernetes]
disabled = false
format = '[$symbol($cluster/$namespace) ]($style)'
style = 'fg:mauve'
symbol = '󱃾 '

[openstack]
disabled = false
format = '[$symbol$cloud(\($project\)) ]($style)'
style = 'fg:mauve'
symbol = ' '

[pulumi]
disabled = false
format = '[$symbol$stack ]($style)'
style = 'fg:blue'

[terraform]
disabled = false
format = '[$symbol$workspace ]($style)'
style = 'fg:mauve'
symbol = '󱁢 '

### COLOR PALETTES
[palettes.catppuccin_latte]
rosewater = '#dc8a78'
flamingo = '#dd7878'
pink = '#ea76cb'
mauve = '#8839ef'
red = '#d20f39'
maroon = '#e64553'
peach = '#fe640b'
yellow = '#df8e1d'
green = '#40a02b'
teal = '#179299'
sky = '#04a5e5'
sapphire = '#209fb5'
blue = '#1e66f5'
lavender = '#7287fd'
text = '#4c4f69'
subtext1 = '#5c5f77'
subtext0 = '#6c6f85'
overlay2 = '#7c7f93'
overlay1 = '#8c8fa1'
overlay0 = '#9ca0b0'
surface2 = '#acb0be'
surface1 = '#bcc0cc'
surface0 = '#ccd0da'
base = '#eff1f5'
mantle = '#e6e9ef'
crust = '#dce0e8'
contrast = '#ffffff'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'
contrast = '#000000'
